- name: Prepare reports folder
  run: mkdir -p reports

- name: Run OWASP ZAP Scan
  run: |
    docker run --rm -v $(pwd)/reports:/zap/wrk/:rw \
      zaproxy/zap-stable \
      zap-baseline.py \
        -t https://www.saucedemo.com \
        -r /zap/wrk/zap_report.html

- name: Upload ZAP Report
  uses: actions/upload-artifact@v4
  with:
    name: ZAP Security Report
    path: reports/zap_report.html