name: Security Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare reports folder
        run: mkdir -p reports

      - name: Run OWASP ZAP Scan
        run: |
          docker run --rm -u root -v $(pwd)/reports:/zap/wrk/:rw \
            zaproxy/zap-stable \
            zap-baseline.py \
              -t https://www.saucedemo.com \
              -r zap_report.html || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Security Report
          path: reports/zap_report.html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          force_orphan: true


  notify-slack:
    needs: zap_scan
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Slack notification
        run: |
          STATUS="${{ needs.zap_scan.result }}"
          EMOJI="❌"
          COLOR="danger"
          if [ "$STATUS" = "success" ]; then
            EMOJI="✅"
            COLOR="good"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"attachments\": [
              {
                \"color\": \"$COLOR\",
                \"mrkdwn_in\": [\"text\"],
                \"text\": \"$EMOJI *OWASP ZAP Security Scan*\n*Repo:* <$GITHUB_SERVER_URL/$GITHUB_REPOSITORY|$GITHUB_REPOSITORY>\n*Branch:* $GITHUB_REF_NAME\n*Commit:* <$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|$GITHUB_SHA>\n*Status:* *$STATUS*\n:clipboard: *Reports:*\n• <https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}/zap_report.html|ZAP Report>\n• <https://github.com/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}|GitHub Actions Logs>\"
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
